311_api_key: ENV["311_API_KEY"]
twitter:
  consumer_key: ENV["TWITTER_CONSUMER_KEY"]
  consumer_secret: ENV["TWITTER_CONSUMER_SECRET"]
  access_token: ENV["TWITTER_ACCESS_TOKEN"]
  access_secret: ENV["TWITTER_ACCESS_SECRET"]